// src/components/Home.jsx
import { Link } from "react-router-dom";
import { FaArrowRight } from "react-icons/fa";
import HighlightText from "./HighlightText";
import CTAButton from "./CTAButton.jsx";
import Banner from "../assets/Images/banner.mp4";
import CodeBlocks from "./CodeBlocks.jsx";
import Footer from "./Footer.jsx";
const Home = () => {
  return (
    <div>
      {/* Section 1 */}

      {/* add shadows */}
      <div className="flex flex-col relative w-full text-white justify-between">
        <Link to="/signup">
          <div className="group mt-16 p-1 mx-auto rounded-full bg-richblack-800 font-bold text-richblack-200 transition-all duration-200 border-b-[1px] border-white border-opacity-20 hover:scale-95 w-fit">
            <div className="rounded-full flex flex-row items-center gap-[10px] px-5 py-[5px] group-hover:bg-richblack-900">
              <p>Become an Instructor</p>
              <FaArrowRight></FaArrowRight>
            </div>
          </div>
        </Link>

        <div className="text-center text-4xl font-semibold mt-7">
          Empower your future with
          <HighlightText text={" Coding Skills"}></HighlightText>
        </div>

        <div className=" mt-4 flex justify-center">
          <p className="w-[70%] text-center font-thin text-[16px] text-richblack-300">
            {" "}
            With our online coding courses, you can learn at your own pace, from
            anywhere in the world, and get access to a wealth of resources,
            including hands-on projects, quizzes, and personalized feedback from
            instructors.
          </p>
        </div>

        <div className="flex flex-row justify-center gap-5 mt-8">
          <CTAButton active={true} linkto={"/signup"}>
            Learn More
          </CTAButton>
          <CTAButton active={false} linkto={"/login"}>
            Book a Demo
          </CTAButton>
        </div>

        <div className="mt-12 mx-3 flex flex-row justify-center">
          <video muted loop autoPlay className="h-[515px] shadow-custom-shadow">
            <source src={Banner} type="video/mp4"></source>
          </video>
        </div>

        {/* code section 1 */}
        <div className="mt-8 px-[120px]">
          <CodeBlocks
            position={"lg:flex-row"}
            heading={
              <div className="text-4xl font-semibold">
                Unlock Your{" "}
                <HighlightText text={" coding potential "}></HighlightText>with
                our online courses
              </div>
            }
            subHeading={
              "Our courses are designed and taught by industry experts who have years of experience in coding and are passionate about sharing their knowledge with you."
            }
            ctabtn1={{
              text: "Try it yourself",
              linkto: "/signup",
              active: true,
            }}
            ctabtn2={{
              text: "Learn More",
              linkto: "/login",
              active: false,
            }}
            codeBlock={`<!DOCTYPE html> 
                        <html> 
                        <head><title>Example</title>
                        <linkrel="stylesheet"href="styles.css"> 
                        </head> 
                        <body> 
                        <h1><ahref="/">Header</a></h1> 
                        <nav>
                        <ahref="one/">One</a><ahref="two/">Two</a><ahref="three/">Three</a> 
                        </nav>`}
            codeColor={"text-yellow-25"}
          ></CodeBlocks>
        </div>

        <div className="px-[120px]">
          <CodeBlocks
            position={"lg:flex-row-reverse"}
            heading={
              <div className="text-4xl font-semibold">
                Start <HighlightText text={" coding "}></HighlightText>
                <br></br>
                <HighlightText text={"in seconds"}></HighlightText>
              </div>
            }
            subHeading={
              "Go ahead, give it a try. Our hands-on learning environment means you'll be writing real code from your very first lesson."
            }
            ctabtn1={{
              text: "Continue Lesson",
              linkto: "/signup",
              active: true,
            }}
            ctabtn2={{
              text: "Learn More",
              linkto: "/login",
              active: false,
            }}
            codeBlock={`<!DOCTYPE html> 
                        <html> 
                        <head><title>Example</title>
                        <linkrel="stylesheet"href="styles.css"> 
                        </head> 
                        <body> 
                        <h1><ahref="/">Header</a></h1> 
                        <nav>
                        <ahref="one/">One</a><ahref="two/">Two</a><ahref="three/">Three</a> 
                        </nav>`}
            codeColor={"text-yellow-25"}
          ></CodeBlocks>
        </div>
      </div>

      {/* Section 2 */}
      {/* Section 3 */}
      {/* Footer */}
      <Footer></Footer>
    </div>
  );
};

export default Home;

// src/app/components/home/home.component.ts
import { Component } from '@angular/core';
import { MatIconModule } from '@angular/material/icon';
import { HighlighttextComponent } from './highlighttext/highlighttext.component';
import { CodeBlocksComponent } from './code-blocks/code-blocks.component';
import { trigger, transition, animate, keyframes, style } from '@angular/animations';


@Component({
  selector: 'app-home',
  standalone: true,
  imports: [MatIconModule, HighlighttextComponent,CodeBlocksComponent],
  templateUrl: './home.component.html',
  styleUrl: './home.component.scss',
})
export class HomeComponent {
  text: string = "Coding Skills "
}

<div
    style="width: 100vw; min-height: 100vh; background: #000814; display: flex; flex-direction: column; font-family: 'Inter', sans-serif;">
    <!-- section1 -->
    <div class="relative mx-auto flex flex-col w-11/12 items-center text-white justify-between max-w-maxContent">
        <div
            class="group mt-16 p-1 mx-auto rounded-full bg-richblack-800 font-bold text-richblack-200 transition-all duration-200 hover:scale-95 w-fit ">
            <div class="flex text-[17px] px-6 py-3 rounded-md font-bold gap-1">
                <button class="text-center ">
                    Became a Instructor</button>
                <mat-icon>arrow_forward</mat-icon>
            </div>
        </div>

        <div class="text-center text-4xl font-semibold mt-7">
            Empower Your Future with
            <app-highlighttext [text]="text"></app-highlighttext>
        </div>

        <div class="w-[90%] text-center text-lg font-bold text-richblack-300 mt-4 ">
            With our online coding courses, you can learn at your own pace ,from anywhere in the world,and get access to
            a wealth of resources , including hands-on projects,quizee and personalized feedback from instructors
        </div>

        <div class="flex flex-row gap-7 mt-8">
            <!-- add-shadows -->
            <button
                class="text-center text-[17px] px-6 py-3 rounded-md font-bold bg-yellow-50 text-black hover:scale-95 transition-all duration-200">
                Learn More</button>
            <button
                class="text-center text-[17px] px-6 py-3 rounded-md font-bold bg-richblack-800 hover:scale-95 transition-all duration-200">
                Book a Demo</button>
        </div>

        <div class="shadow-blue-200 mx-3 my-12">
            <video muted loop autoplay class="size">
                <source [src]="'assets/Images/banner.mp4'" type="video/mp4">
            </video>
        </div>

        <div class="flex flex-row w-[90%] justify-between gap-10 my-20">
            <div class="flex flex-col w-[50%] gap-8">
                <div class="text-4xl font-bold">
                    Unlock
                    <app-highlighttext [text]="'Coding Potential'"></app-highlighttext>
                    with our online courses
                </div>
                <div class="text-richblack-300 font-bold">
                    Our courses are designed and taught by industry experts who have years of experience in coding
                    and are passionate about sharing their knowledge with you.
                </div>
                <div class="flex flex-row gap-7 mt-7">
                    <div
                        class="flex text-[17px] px-6 py-3 rounded-md font-bold bg-yellow-50 text-black hover:scale-95 transition-all duration-200 gap-1">
                        <button class="text-center ">
                            Try it yourself</button>
                        <mat-icon>arrow_forward</mat-icon>
                    </div>
                    <button
                        class="text-center text-[17px] px-6 py-3 rounded-md font-bold bg-richblack-800 hover:scale-95 transition-all duration-200">
                        Learn More</button>
                </div>
            </div>

            <!-- coding block 1 -->
            <div class="flex flex-row text-[15px] w-[50%] gap-4 h-fit">
                <div class="text-center flex flex-col w-[10%] text-richblack-400 font-inter font-bold">
                    <p>1</p>
                    <p>2</p>
                    <p>3</p>
                    <p>4</p>
                    <p>5</p>
                    <p>6</p>
                    <p>7</p>
                    <p>8</p>
                    <p>9</p>
                </div>
                <div class="w-[90%] flex flex-col font-bold font-mono text-yellow-25 gap-3">
                    <div>&lt;!DOCTYPE html&gt;</div>
                    <div>&lt;html&gt;</div>
                    <div>&lt;head&gt;</div>
                    <div>&lt;title&gt;Example&lt;/title&gt;</div>
                    <div>&lt;/head&gt;</div>
                    <div>&lt;body&gt;</div>
                    <div>&lt;p&gt;This is an example text.&lt;/p&gt;</div>
                    <div>&lt;/body&gt;</div>
                    <div>&lt;/html&gt;</div>
                </div>
            </div>

        </div>

        <div class="flex flex-row-reverse w-[90%] justify-between gap-10 my-20">
            <div class="flex flex-col w-[50%] gap-8">
                <div class="text-4xl font-bold">
                    Start
                    <app-highlighttext [text]="'coding in seconds'"></app-highlighttext>
                </div>
                <div class="text-richblack-300 font-bold">
                    Go ahead, give it a try. Our hands-on learning environment means you'll be writing real code from
                    your very first lesson.
                </div>
                <div class="flex flex-row gap-7 mt-7">
                    <div
                        class="flex text-[17px] px-6 py-3 rounded-md font-bold bg-yellow-50 text-black hover:scale-95 transition-all duration-200 gap-1">
                        <button class="text-center ">
                            Continue Lession</button>
                        <mat-icon>arrow_forward</mat-icon>
                    </div>

                    <button
                        class="text-center text-[17px] px-6 py-3 rounded-md font-bold bg-richblack-800 hover:scale-95 transition-all duration-200">
                        Learn More</button>
                </div>
            </div>

            <div class="flex flex-row text-[15px] w-[50%] gap-4 h-fit">
                <div class="text-center flex flex-col w-[10%] text-richblack-400 font-inter font-bold">
                    <p>1</p>
                    <p>2</p>
                    <p>3</p>
                    <p>4</p>
                    <p>5</p>
                    <p>6</p>
                    <p>7</p>
                    <p>8</p>
                    <p>9</p>
                </div>
                <div class="w-[90%] flex flex-col font-bold font-mono text-yellow-25 gap-3">
                    <div>&lt;!DOCTYPE html&gt;</div>
                    <div>&lt;html&gt;</div>
                    <div>&lt;head&gt;</div>
                    <div>&lt;title&gt;Example&lt;/title&gt;</div>
                    <div>&lt;/head&gt;</div>
                    <div>&lt;body&gt;</div>
                    <div>&lt;p&gt;This is an example text.&lt;/p&gt;</div>
                    <div>&lt;/body&gt;</div>
                    <div>&lt;/html&gt;</div>
                </div>
            </div>
        </div>
    </div>
</div>
